### ISSUE TITLE
Fleet gitRepo helm chart download via OCI:// x509 error

### ISSUE THREAD

**Issue by kkaempf** [rancher/fleet#1520]
### Issue description:

The customer is trying to install a helm chart via Fleet using their internal Harbor instance via OCI (since chart museum is deprecated). They're getting a x509 certificate signed by unknown authority message in the fleet container when downloading the chart over OCI.

They followed the instructions for setting up the secret (https://fleet.rancher.io/gitrepo-add#using-private-helm-repositories), and specifying it in helmSecretName. 

### Business impact:
At the moment this is preventing the customer from delivering a MVP to internal customers for developing on Rancher platform. They are trying to work with their infosec team to externally access the chart, but at present on-prem OCI registry is their only option. Effectively they are blocked using fleet until they have a resolution.

### Troubleshooting steps:
We suspected that Fleet couldn’t verify the TLS certificate because it’s self-signed or signed by a private CA. We tried to make the verification work by passing the CA certificate to the GitRepo.

The customer also tried to configure it to trust all certificates by editing the GitRepo in the UI, and selecting "Accept any certificate (insecure)" option in the TLS Certificate Verification drop down. They still saw the problem.

The step-git-source container is not having an issue.

### Actual behavior:
The x509 error coming from the fleet container when downloading the chart over OCI.

### Expected behavior:
Download the OCI chart without error

Files, logs, traces:

-- see SURE-6170 --

Additional notes:
From the customer:

When looking at the source code, [getContent](https://github.com/rancher/fleet/blob/34374a6e2d91279c91b1e3a4a7f76c73fc08c64a/pkg/bundlereader/loaddirectory.go#L61) and [downloadOCIChart](https://github.com/rancher/fleet/blob/34374a6e2d91279c91b1e3a4a7f76c73fc08c64a/pkg/bundlereader/loaddirectory.go#L165) uses the helm module to download the chart since it is OCI://.

Notice in the message how the the schema in the URI is not OCI, but HTTPS? That's why it seems like the downloadOCIChart function is not the issue, but somewhere later on in the calling function.
 
The error message we're getting though is for https://,  which makes it seem like it's coming from the httpgetters called later on in getContent. In fact, I'm wondering why those calls are made if the OCI chart is already downloaded. But I'm no Go expert, so I'm probably missing something!

**Comment by manno** [comment]
Since the x509 error message appears in the fleet container's logs, I think this is related to [imagescan](https://fleet.rancher.io/imagescan). The [imagescan controller](https://github.com/rancher/fleet/blob/master/pkg/controllers/image/image.go#L85) does not know how to handle OCI.

**Comment by weyfonk** [comment]
This should be fixed by #1591.

**Comment by sbulage** [comment]
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---
|1| Test helm pacakge get installed when `oci://` using the authentication.
|2| Test helm pacakge get installed when `https://` using the TLS and CA Certs.
|3| Test helm pacakge get installed when `oci://` without using any authentication method.

**Comment by sbulage** [comment]
Below scenario's are performed using:
* Chartmuseum
* Ngrok
* Certificates are created using the existing fleet [scripts](https://github.com/rancher/fleet/blob/master/.github/scripts/create-zot-certs.sh)
* `ghcr.io` `OCI` registry is used.

Scenarios
|Scenario|Test Case|Result
|---|---|---
|1| Test helm pacakge get installed when `oci://` using the authentication.| :white_check_mark:|
|2| Test helm pacakge get installed when `https://` using the TLS and CA Certs.| :white_check_mark:|
|3| Test helm pacakge get installed when `oci://` without using any authentication method.| :white_check_mark:|

**Comment by sbulage** [comment]
> Below scenario's are performed using:
> 
> * Chartmuseum
> * Ngrok
> * Certificates are created using the existing fleet [scripts](https://github.com/rancher/fleet/blob/master/.github/scripts/create-zot-certs.sh)
> * `ghcr.io` `OCI` registry is used.
> 
> Scenarios
> 
> Scenario	Test Case	Result
> 1	Test helm pacakge get installed when `oci://` using the authentication.	
> 2	Test helm pacakge get installed when `https://` using the TLS and CA Certs.	
> 3	Test helm pacakge get installed when `oci://` without using any authentication method.

All above scenario's are already covered in the e2e tests using `Zot registry`. I gave a try using chartmuseum, ngrok and TLS certs etc.

**Comment by sbulage** [comment]
I have tried another scenario but it didn't give o/p as expected. The reason behind is that OCI registry behind HTTPS was already there and I was trying to achieve it in a different way.

**Comment by JannikZed** [comment]
As we are facing the same issue as well: is there already a fleet version known, where this bug is fixed?

**Comment by weyfonk** [comment]
Hi, yes, this has been fixed in Fleet [v0.8.0](https://github.com/rancher/fleet/releases/tag/v0.8.0).

**Comment by upics** [comment]
Hi, i think there is still an issue when using `chart: "oci://{registry}"`: when the registry is not configured to receive https calls, fleet return this error: 

`time="2024-08-02T11:23:26Z" level=fatal msg="Get \"https://{registry}/v2/\": http: server gave HTTP response to HTTPS client"`.

There should be a way in order to make plain-http request to the registry when the oci registry is not configured to receive https calls.
