### ISSUE TITLE
Fix Fleet post renderer errors with non-trivial kustomize git repo

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#161]
Fleet reports post renderer errors with various non-trivial kustomize git repos such as [this](https://github.com/ron1/fleet-examples/tree/expose-fleet-mc-kustomize-example-post-renderer-bug/multi-cluster/kustomize) which includes modifications to the multi-cluster kustomize example to mimic various real-world kustomize repos.

Steps to reproduce the problem:
1. `git clone -b  expose-fleet-mc-kustomize-example-post-renderer-bug https://github.com/ron1/fleet-examples.git`
2. `cd fleet-examples/multi-cluster/kustomize`
3. `kustomize build overlays/dev` - verifies that kustomize successfully builds the dev overlay in this repo
4. `fleet test -t dev` - reports the following unexpected error:
```
# Matched: dev
FATA[0000] error while running post render on files: obj '{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"labels": {"app": "catalog-operator"},
    "name": "catalog-operator", "namespace": "olm"}, "spec": {"replicas": 1, "selector": {
      "matchLabels": {"app": "catalog-operator"}}, "strategy": {"type": "RollingUpdate"},
    "template": {"metadata": {"labels": {"app": "catalog-operator"}}, "spec": {"containers": [
          {"args": ["-namespace", "olm", "-configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest",
              "-util-image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607"],
            "command": ["/bin/catalog"], "env": "image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607": "imagePullPolicy",
            "IfNotPresent": "livenessProbe", ? {"httpGet": {"path": "/healthz", "port": 8080}}
            : "name", "catalog-operator": "ports", ? [{"containerPort": 8080}, {"containerPort": 8081,
                "name": "metrics", "protocol": "TCP"}] : "readinessProbe", ? {"httpGet": {
                "path": "/healthz", "port": 8080}} : "resources", ? {"requests": {
                "cpu": "10m", "memor' at path 'spec/template/spec/containers/env/valueFrom/configMapKeyRef/name': visit traversal on path: [env valueFrom configMapKeyRef name]: expected sequence or mapping node
```

Note that when I define a GitRepo for this branch with path multi-cluster/kustomize, its `status.resourceErrors`  is updated as listed below. 

```
status:
  resourcesErrors:
  - |-
    error while running post render on files: obj '{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"labels": {"app": "catalog-operator"},
    "name": "catalog-operator", "namespace": "olm"}, "spec": {"replicas": 1, "selector": {
      "matchLabels": {"app": "catalog-operator"}}, "strategy": {"type": "RollingUpdate"},
    "template": {"metadata": {"labels": {"app": "catalog-operator"}}, "spec": {"containers": [
          {"args": ["-namespace", "olm", "-configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest",
              "-util-image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607"],
            "command": ["/bin/catalog"], "env": "image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607": "imagePullPolicy",
            "IfNotPresent": "livenessProbe", ? {"httpGet": {"path": "/healthz", "port": 8080}}
            : "name", "catalog-operator": "ports", ? [{"containerPort": 8080}, {"containerPort": 8081,
                "name": "metrics", "protocol": "TCP"}] : "readinessProbe", ? {"httpGet": {
                "path": "/healthz", "port": 8080}} : "resources", ? {"requests": {
                "cpu": "10m", "memor' at path 'spec/template/spec/containers/env/valueFrom/configMapKeyRef/name': visit traversal on path: [env valueFrom configMapKeyRef name]: expected sequence or mapping node
  - |-
    error while running post render on files: obj '{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"labels": {"app": "catalog-operator"},
    "name": "catalog-operator", "namespace": "olm"}, "spec": {"replicas": 1, "selector": {
      "matchLabels": {"app": "catalog-operator"}}, "strategy": {"type": "RollingUpdate"},
    "template": {"metadata": {"labels": {"app": "catalog-operator"}}, "spec": {"containers": [
          {"args": ["-namespace", "olm", "-configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest",
              "-util-image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607"],
            "command": ["/bin/catalog"], "env": "image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607": "imagePullPolicy",
            "IfNotPresent": "livenessProbe", ? {"httpGet": {"path": "/healthz", "port": 8080}}
            : "name", "catalog-operator": "ports", ? [{"containerPort": 8080}, {"containerPort": 8081,
                "name": "metrics", "protocol": "TCP"}] : "readinessProbe", ? {"httpGet": {
                "path": "/healthz", "port": 8080}} : "resources", ? {"requests": {
                "cpu": "10m", "memor' at path 'spec/template/spec/containers/env/valueFrom/configMapKeyRef/name': visit traversal on path: [env valueFrom configMapKeyRef name]: expected sequence or mapping node
  - |-
    error while running post render on files: obj '{"apiVersion": "apps/v1", "kind": "Deployment", "metadata": {"labels": {"app": "catalog-operator"},
    "name": "catalog-operator", "namespace": "olm"}, "spec": {"replicas": 1, "selector": {
      "matchLabels": {"app": "catalog-operator"}}, "strategy": {"type": "RollingUpdate"},
    "template": {"metadata": {"labels": {"app": "catalog-operator"}}, "spec": {"containers": [
          {"args": ["-namespace", "olm", "-configmapServerImage=quay.io/operator-framework/configmap-operator-registry:latest",
              "-util-image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607"],
            "command": ["/bin/catalog"], "env": "image", "quay.io/operator-framework/olm@sha256:de396b540b82219812061d0d753440d5655250c621c753ed1dc67d6154741607": "imagePullPolicy",
            "IfNotPresent": "livenessProbe", ? {"httpGet": {"path": "/healthz", "port": 8080}}
            : "name", "catalog-operator": "ports", ? [{"containerPort": 8080}, {"containerPort": 8081,
                "name": "metrics", "protocol": "TCP"}] : "readinessProbe", ? {"httpGet": {
                "path": "/healthz", "port": 8080}} : "resources", ? {"requests": {
                "cpu": "10m", "memor' at path 'spec/template/spec/containers/env/valueFrom/configMapKeyRef/name': visit traversal on path: [env valueFrom configMapKeyRef name]: expected sequence or mapping node
```

**Comment by ron1** [comment]
@StrongMonkey I suspect this is a problem with the version of kustomize bundled within Fleet. I believe an upgrade to kustomize v3.8.7 with kustomize/api v0.6.5 and kustomize/kyaml v0.9.4 will fix this problem. Any chance the kustomize version bundled within Fleet can be refreshed in the next Fleet version?

**Comment by StrongMonkey** [comment]
@ron1 Did you fix the issue eventually? I believe you have to make two things right. First is to make sure you choose fleet-local workspace since the example is in fleet-local workspace. Second is to make sure your cluster has one of label `env: dev`, `env: test` or `env: prod`.

**Comment by ron1** [comment]
@StrongMonkey This problem occurs even after your suggestions are applied. Have you tried to reproduce the problem using my patched branch? The problem seems related to kustomize reporting WARNINGS for the supplied manifests. The version of kustomize embedded in fleet 0.3.1, namely 3.8.3, reports these warnings. Kustomize 3.8.7 no longer reports warnings. I suspect the warnings being sent to stdout/stderr are confusing the post renderer and thereby corrupting its output.

Pls let me know if you are unable to reproduce the problem using my custom branch.

**Comment by ron1** [comment]
Also note that others on slack have encountered this issue as well. Again the key point here is that the kustomize-generated WARNING appears within the GitRepo status resource error text.

**Comment by StrongMonkey** [comment]
@ron1 This should be fixed in the latest v0.3.4 by https://github.com/rancher/fleet/pull/262. Free free to open it if you are seeing it again.

**Comment by ron1** [comment]
@StrongMonkey The reproduction case I provided above still fails with v0.3.4. After some additional investigation, I believe the root cause of this issue is kustomize bug https://github.com/kubernetes-sigs/kustomize/issues/2960  which is fixed in a later version of kustomize via PR https://github.com/kubernetes-sigs/kustomize/pull/2983.

Please re-open this issue for me and mark it as dependent upon Kustomize upgrade issue https://github.com/rancher/fleet/issues/287.

**Comment by StrongMonkey** [comment]
@ron1 The kustomize version upgrade is available in the latest version of fleet(v0.3.5-rc4). Are you able to provide an example to test this bug?

**Comment by ron1** [comment]
@StrongMonkey See the 4 steps listed below the "Steps to reproduce the problem:" (here)[https://github.com/rancher/fleet/issues/161#issue-751009614]. If I go ahead and verify that fleet v0.3.5-rc4 fixes this issue, would you consider reviewing this (PR)[https://github.com/rancher/fleet/pull/303] for me?:wink:

**Comment by ron1** [comment]
@StrongMonkey It appears `fleet_0.3.5-rc4_linux_amd64 test` is completely broken in this build. All attempted uses of the `test` subcommand result in the error below. This is a blocker for my ability to verify the new kustomize v3.8.10 functionality.

```
$ fleet_0.3.5-rc4_linux_amd64 test -t dev
panic: unable to redefine 'n' shorthand in "test" flagset: it's already used for "cluster-name" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0009cc400, 0xc0007681e0)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x6f0
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc0007681e0)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:887 +0xa8
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc0009cc300, 0xc000b0fb40)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x94
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc0009cc400, 0xc0009cc300)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:885 +0x58
github.com/spf13/cobra.(*Command).mergePersistentFlags(0xc00072c2c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:1642 +0x92
github.com/spf13/cobra.stripFlags(0xc0001d2180, 0x2, 0x2, 0xc00072c2c0, 0x0, 0x2, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:562 +0x5a
github.com/spf13/cobra.(*Command).Find.func1(0xc00072c2c0, 0xc0001d2180, 0x2, 0x2, 0x4, 0xc0001d2180, 0x2, 0x2)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:621 +0x5c
github.com/spf13/cobra.(*Command).Find.func1(0xc00072d8c0, 0xc00013e050, 0x3, 0x3, 0x18a89ef, 0xc0009f8b00, 0xc0002f5800, 0xa)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:629 +0x11e
github.com/spf13/cobra.(*Command).Find(0xc00072d8c0, 0xc00013e050, 0x3, 0x3, 0x2, 0xc0003fc000, 0x88, 0xc0009f8840, 0xc000b0fe48, 0x18a8445)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:634 +0x8c
github.com/spf13/cobra.(*Command).initCompleteCmd(0xc00072d8c0, 0xc00013e050, 0x3, 0x3)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/custom_completions.go:167 +0x2cb
github.com/spf13/cobra.(*Command).ExecuteC(0xc00072d8c0, 0xc000136010, 0x2e37d20, 0xc00013e900)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:927 +0x10b
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/rancher/wrangler-cli.Main(0xc00072d8c0)
	/go/pkg/mod/github.com/rancher/wrangler-cli@v0.0.0-20200815040857-81c48cf8ab43/builder.go:73 +0x6d
main.main()
	/go/src/github.com/rancher/fleet/main.go:19 +0x2a
```

**Comment by ron1** [comment]
I will go ahead and open a `fleet test` regression bug for fleet version 0.3.5-rc4.

**Comment by StrongMonkey** [comment]
I probably broke it. Please open a bug and I will fix it. At the same time you should try v0.3.5-rc3 which also has the fix.

**Comment by ron1** [comment]
Fleet test bug is [here](https://github.com/rancher/fleet/issues/336).

**Comment by ron1** [comment]
I can confirm that Fleet 0.3.5-rc3 fixes this problem which was introduced in kustomize v3.8.2 and corrected in v3.8.7+.
